DefaultContentLanguage = "en"
baseURL = "https://www.centcolschallenge.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
languageCode = "en"
title = "Cent Cols Challenge"
theme = "ccc-v5"

[imaging]
disableDate = true
disableLatLong = true
quality = 90